[tool.poetry]
name = "bot-kuraku"
version = "1.0.0"
description = "bot-kuraku"
authors = ["ssttkkl <huang.wen.long@hotmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
nonebot2 = "^2.0.0rc1"
nonebot-adapter-onebot = "^2.1.5"
nonebot-plugin-pixivbot = {extras = ["onebot"], version = "^1.4.0rc3"}
nonebot-plugin-mahjong-utils = "^0.1.3"
nonebot-plugin-onebot-monitor = "^0.1.0"
nonebot-plugin-treehelp = ">=0.0.1"

[tool.poetry.dev-dependencies]
nb-cli = "^0.6.7"

[tool.nonebot]
plugins = ["nonebot_plugin_treehelp", "nonebot_plugin_pixivbot", "nonebot_plugin_mahjong_utils", "nonebot_plugin_onebot_monitor"]

[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
